# Generated by Django 2.2.1 on 2019-05-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_car', models.DateField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('currentLocation', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('purchaseDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
